language: php

php:
  - '7.3'

matrix:
  fast_finish: true

before_install:
  - composer install --prefer-dist --no-interaction --dev

jobs:
  include:
    - name: "Unit tests"
      script: php vendor/bin/phpunit --configuration tests/Unit/phpunit.xml.dist
    - name: "Code style"
      script: php vendor/bin/phpcs --standard=psr12 src/ --ignore=*.min.css
    - name: "Tests code style"
      script: php vendor/bin/phpcs --standard=psr12 tests/ --ignore=/_files/ -n

